name: Java CI / CD with Gradle

env:
  S3_BUCKET_NAME: realworld-s3-bucket

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
      env:
        REALWORLD_MYSQL_JDBC_URL: ${{secrets.REALWORLD_MYSQL_JDBC_URL}}
        REALWORLD_MYSQL_USERNAME: ${{secrets.REALWORLD_MYSQL_USERNAME}}
        REALWORLD_MYSQL_PASSWORD: ${{secrets.REALWORLD_MYSQL_PASSWORD}}

    - name: Make zip file
      run: zip -r ./realWorld.zip *

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Upload to S3
      run: aws s3 cp --region us-east-1 ./realWorld.zip s3://$S3_BUCKET_NAME/realWorld.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name realWorld --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name realworld-single-deploy --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=realWorld.zip